export var TRELLIS_CONFIG = {
	GUID: 'trellis@trellis.org',
	ID: 'trellis', // used for db filename, etc.
	CLIENT_NAME: 'Trellis',
	DOMAIN_NAME: 'trellis.org',
	PRODUCER: 'Digital Scholar',
	PRODUCER_URL: 'https://digitalscholar.org',
	REPOSITORY_URL: 'https://repo.trellis.org/repo/',
	BASE_URI: 'http://trellis.org/',
	WWW_BASE_URL: 'https://www.trellis.org/',
	PROXY_AUTH_URL: 'https://trellisproxycheck.s3.amazonaws.com/test',
	API_URL: 'https://api.trellis.org/',
	STREAMING_URL: 'wss://stream.trellis.org/',
	SERVICES_URL: 'https://services.trellis.org/',
	API_VERSION: 3,
	CONNECTOR_MIN_VERSION: '5.0.39', // show upgrade prompt for requests from below this version
	PREF_BRANCH: 'extensions.trellis.',
	BOOKMARKLET_ORIGIN: 'https://www.trellis.org',
	BOOKMARKLET_URL: 'https://www.trellis.org/bookmarklet/',
	START_URL: "https://www.trellis.org/start",
	QUICK_START_URL: "https://www.trellis.org/support/quick_start_guide",
	PDF_TOOLS_URL: "https://www.trellis.org/download/xpdf/",
	SUPPORT_URL: "https://www.trellis.org/support/",
	SYNC_INFO_URL: "https://www.trellis.org/support/sync",
	TROUBLESHOOTING_URL: "https://www.trellis.org/support/getting_help",
	FEEDBACK_URL: "https://forums.trellis.org/",
	CONNECTORS_URL: "https://www.trellis.org/download/connectors",
	CHANGELOG_URL: "https://www.trellis.org/support/changelog",
	CREDITS_URL: 'https://www.trellis.org/support/credits_and_acknowledgments',
	LICENSING_URL: 'https://www.trellis.org/support/licensing',
	GET_INVOLVED_URL: 'https://www.trellis.org/getinvolved',
	DICTIONARIES_URL: 'https://download.trellis.org/dictionaries/',
	PLUGINS_URL: 'https://www.trellis.org/support/plugins',
	NEW_FEATURES_URL: 'https://www.trellis.org/blog/trellis-{version}/',
	READ_ALOUD_URL: 'https://www.trellis.org/settings/readaloud'
};
